version: "3"
services:
  # back:
  #   env_file:
  #     - .env
  #   build:
  #     context: .
  #     dockerfile: ./docker/Dockerfile.bapp
  #     args:
  #       - DOPPLER_TOKEN=dp.st.dev.GE5Du4fglZXraBoWQoe5itF3NnHkqBE33t0LjSWb8mN
  #   ports:
  #     - 3000:5000
  front:
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./docker/Dockerfile.frapp
      args:
        - DOPPLER_TOKEN=dp.st.dev.GE5Du4fglZXraBoWQoe5itF3NnHkqBE33t0LjSWb8mN
    ports:
      - 5000:80
   
